Rebuilt the Project with Gradle

diff --git a/.github/workflows/run-unit-tests.yaml b/.github/workflows/run-unit-tests.yaml
--- a/.github/workflows/run-unit-tests.yaml
+++ b/.github/workflows/run-unit-tests.yaml
@@ -1,4 +1,4 @@
-name: SayIt Continuous Integration
+name: SayIt Continous Integration
 
 on: [push]
 
@@ -19,12 +19,22 @@ jobs:
         with:
           distribution: 'temurin'
           java-version: '11'
-      
-      - name: Compile Java Classes
-        run: javac -cp .:lib/*:src src/**/*.java -d bin
 
-      - name: Compile Unit Tests
-        run: javac -cp .:lib/*:bin:src tests/**/*.java -d bin
+      - name: Validate Gradle wrapper
+        uses: gradle/wrapper-validation-action@v1
 
-      - name: Run Unit Tests
-        run: java -jar lib/junit-platform-console-standalone-1.9.3.jar -cp lib/json-20230227.jar:bin --scan-class-path
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v2
+
+      # build everything (includes running unit tests)
+      - name: Execute Gradle build
+        run: ./gradlew build
+
+      # report the results
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+          detailed_summary: true # display detailed summary of the report
+          include_passed: true # include passed tests in the results table
